In [1]:
import scipy 
from scipy import stats as stats
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('Cutlets.csv')
data

Unit A  Unit B
0   6.8090  6.7703
1   6.4376  7.5093
2   6.9157  6.7300
3   7.3012  6.7878
4   7.4488  7.1522
5   7.3871  6.8110
6   6.8755  7.2212
7   7.0621  6.6606
8   6.6840  7.2402
9   6.8236  7.0503
10  7.3930  6.8810
11  7.5169  7.4059
12  6.9246  6.7652
13  6.9256  6.0380
14  6.5797  7.1581
15  6.8394  7.0240
16  6.5970  6.6672
17  7.2705  7.4314
18  7.2828  7.3070
19  7.3495  6.7478
20  6.9438  6.8889
21  7.1560  7.4220
22  6.5341  6.5217
23  7.2854  7.1688
24  6.9952  6.7594
25  6.8568  6.9399
26  7.2163  7.0133
27  6.6801  6.9182
28  6.9431  6.3346
29  7.0852  7.5459
30  6.7794  7.0992
31  7.2783  7.1180
32  7.1561  6.6965
33  7.3943  6.5780
34  6.9405  7.3875

In [3]:
data1 = data['Unit A']
data1

0     6.8090
1     6.4376
2     6.9157
3     7.3012
4     7.4488
5     7.3871
6     6.8755
7     7.0621
8     6.6840
9     6.8236
10    7.3930
11    7.5169
12    6.9246
13    6.9256
14    6.5797
15    6.8394
16    6.5970
17    7.2705
18    7.2828
19    7.3495
20    6.9438
21    7.1560
22    6.5341
23    7.2854
24    6.9952
25    6.8568
26    7.2163
27    6.6801
28    6.9431
29    7.0852
30    6.7794
31    7.2783
32    7.1561
33    7.3943
34    6.9405
Name: Unit A, dtype: float64

In [4]:
data2 = data['Unit B']
data2

0     6.7703
1     7.5093
2     6.7300
3     6.7878
4     7.1522
5     6.8110
6     7.2212
7     6.6606
8     7.2402
9     7.0503
10    6.8810
11    7.4059
12    6.7652
13    6.0380
14    7.1581
15    7.0240
16    6.6672
17    7.4314
18    7.3070
19    6.7478
20    6.8889
21    7.4220
22    6.5217
23    7.1688
24    6.7594
25    6.9399
26    7.0133
27    6.9182
28    6.3346
29    7.5459
30    7.0992
31    7.1180
32    6.6965
33    6.5780
34    7.3875
Name: Unit B, dtype: float64

In [5]:
 p_ttest = stats.ttest_ind(data1, data2)
print(data1, data2)
    

0     6.8090
1     6.4376
2     6.9157
3     7.3012
4     7.4488
5     7.3871
6     6.8755
7     7.0621
8     6.6840
9     6.8236
10    7.3930
11    7.5169
12    6.9246
13    6.9256
14    6.5797
15    6.8394
16    6.5970
17    7.2705
18    7.2828
19    7.3495
20    6.9438
21    7.1560
22    6.5341
23    7.2854
24    6.9952
25    6.8568
26    7.2163
27    6.6801
28    6.9431
29    7.0852
30    6.7794
31    7.2783
32    7.1561
33    7.3943
34    6.9405
Name: Unit A, dtype: float64 0     6.7703
1     7.5093
2     6.7300
3     6.7878
4     7.1522
5     6.8110
6     7.2212
7     6.6606
8     7.2402
9     7.0503
10    6.8810
11    7.4059
12    6.7652
13    6.0380
14    7.1581
15    7.0240
16    6.6672
17    7.4314
18    7.3070
19    6.7478
20    6.8889
21    7.4220
22    6.5217
23    7.1688
24    6.7594
25    6.9399
26    7.0133
27    6.9182
28    6.3346
29    7.5459
30    7.0992
31    7.1180
32    6.6965
33    6.5780
34    7.3875
Name: Unit B, dtype: float64


In [6]:
print("Independent samples t-test p-value:", p_ttest)

Independent samples t-test p-value: Ttest_indResult(statistic=0.7228688704678063, pvalue=0.4722394724599501)


In [7]:
print(p_ttest)

Ttest_indResult(statistic=0.7228688704678063, pvalue=0.4722394724599501)


In [73]:
alpha = 0.5  # Significance level


print("There is no significant difference in the diameter of the cutlets between the two units.")


There is no significant difference in the diameter of the cutlets between the two units.


In [9]:
 # Significance level

#if p_ttest < alpha:
#print("There is a significant difference in the diameter of the cutlets between the two units.")
#else:
#print("There is no significant difference in the diameter of the cutlets between the two units.")


Q2


In [10]:
import pandas as pd
import scipy.stats as stats



In [11]:
data = pd.read_csv("C:\\Users\\Admin\\Desktop\\ASSIGNMENT\\LabTAT.csv")

In [12]:
data.head()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60

In [13]:
p_value=stats.f_oneway(data.iloc[:,0],data.iloc[:,1],data.iloc[:,2],data.iloc[:,3])

In [14]:
p_value

F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)

In [15]:
p_value[1]

2.1156708949992414e-57

Q3



In [16]:
import pandas as pd 
from scipy import stats

In [17]:
data1 = pd.read_csv("C:\\Users\\Admin\\Desktop\\ASSIGNMENT\\BuyerRatio.csv")

In [18]:
data1

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [19]:
data1_table=data1.iloc[:,1:6]
data1_table

East  West  North  South
0    50   142    131     70
1   435  1523   1356    750

In [20]:
data1_table.values

array([[  50,  142,  131,   70],
       [ 435, 1523, 1356,  750]], dtype=int64)

In [21]:
p1=stats.chi2_contingency(data1_table)

In [22]:
p1

Chi2ContingencyResult(statistic=1.595945538661058, pvalue=0.6603094907091882, dof=3, expected_freq=array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
       [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [23]:
type(p1)

scipy.stats.contingency.Chi2ContingencyResult

In [28]:

no_of_rows=len(data1_table.iloc[0:2,0])
no_of_columns=len(data1_table.iloc[0,0:4])
degree_of_f=(no_of_rows-1)*(no_of_columns-1)
print('Degree of Freedom=',degree_of_f)

Degree of Freedom= 3


In [31]:
Expected_value = p1[3]
Expected_value

array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
       [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]])

In [36]:
from scipy.stats import chi2
chi_square=sum([(o-e)**2/e for o,e in zip(data1_table.values,Expected_value)])
chi_square_statestic=chi_square[0]+chi_square[1]
chi_square_statestic


1.5152956451130446

In [41]:

if p_value < alpha:
    print("Reject Null Hypothesis: The male-female buyer ratios are not similar across regions.")
else:
    print("Failed to reject Null Hypothesis: The male-female buyer ratios are similar across regions.")

Failed to reject Null Hypothesis: The male-female buyer ratios are similar across regions.


Q4)   TeleCall uses 4 centers around the globe to process customer order forms. They audit a certain %  of the customer order forms. Any error in order form renders it defective and has to be reworked before processing.  The manager wants to check whether the defective %  varies by centre. Please analyze the data at 5% significance level and help the manager draw appropriate inferences

In [43]:
data2 = pd.read_csv("C:\\Users\\Admin\\Desktop\\ASSIGNMENT\\Costomer+OrderForm.csv")

In [44]:
data2

Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]

In [59]:
data2_table = data2.iloc[:,1:4]


In [60]:
data2_table

Indonesia       Malta       India
0    Error Free   Defective  Error Free
1    Error Free  Error Free   Defective
2     Defective   Defective  Error Free
3    Error Free  Error Free  Error Free
4    Error Free   Defective  Error Free
..          ...         ...         ...
295  Error Free  Error Free  Error Free
296  Error Free  Error Free  Error Free
297  Error Free   Defective  Error Free
298  Error Free  Error Free  Error Free
299   Defective   Defective  Error Free

[300 rows x 3 columns]

In [64]:
data2.value_counts()

Phillippines  Indonesia   Malta       India     
Error Free    Error Free  Error Free  Error Free    206
Defective     Error Free  Error Free  Error Free     21
Error Free    Defective   Error Free  Error Free     20
              Error Free  Defective   Error Free     18
                          Error Free  Defective      16
              Defective   Defective   Error Free      9
Defective     Error Free  Defective   Error Free      4
              Defective   Error Free  Error Free      2
              Error Free  Error Free  Defective       2
Error Free    Defective   Error Free  Defective       2
dtype: int64

In [65]:
data2.Phillippines.value_counts()

Error Free    271
Defective      29
Name: Phillippines, dtype: int64

In [66]:
data2.Indonesia.value_counts()

Error Free    267
Defective      33
Name: Indonesia, dtype: int64

In [67]:
data2.Malta.value_counts("")

Error Free    269
Defective      31
Name: Malta, dtype: int64

In [68]:
data2.India.value_counts()

Error Free    280
Defective      20
Name: India, dtype: int64

In [71]:
obs=np.array([[271,267,269,280],[29,33,31,20]])

In [72]:
obs #contingency table to know how many error free and defective values

array([[271, 267, 269, 280],
       [ 29,  33,  31,  20]])

In [76]:
p2 = stats.chi2_contingency(obs)

In [77]:
p2

Chi2ContingencyResult(statistic=3.858960685820355, pvalue=0.2771020991233135, dof=3, expected_freq=array([[271.75, 271.75, 271.75, 271.75],
       [ 28.25,  28.25,  28.25,  28.25]]))

In [79]:
#therefore we accept the data p value> 0.5